-- ==========================================
-- 1. EXTENSIONS & DROPS (IDEMPOTENCY)
-- ==========================================
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

-- ==========================================
-- 2. TABLES
-- ==========================================

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text unique not null,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default now()
);

create table if not exists public.menu (
  id bigint generated by default as identity primary key,
  name text not null,
  weight text,
  ingredients text,
  description text,
  price float8 not null check (price >= 0),
  active boolean default true,
  file_name text,
  category text check (category in ('burgers', 'drinks', 'combos', 'soups', 'desserts', 'salads')),
  created_at timestamp with time zone default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  total_price float8 default 0.0,
  state text default 'pending' check (state in ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled')),
  order_time timestamp with time zone default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  menu_id bigint references public.menu(id) on delete set null,
  quantity int not null check (quantity > 0),
  unit_price float8 not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  time_start timestamp with time zone not null,
  type_table text,
  user_id uuid references public.users(id) on delete cascade,
  status text default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamp with time zone default now()
);

-- ==========================================
-- 3. SECURITY (RLS POLICIES)
-- ==========================================

alter table public.users enable row level security;
alter table public.menu enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reservations enable row level security;

-- Clean old policies
drop policy if exists "Public read menu" on public.menu;
drop policy if exists "Users manage own profiles" on public.users;
drop policy if exists "Users read own orders" on public.orders;
drop policy if exists "Users read own reservations" on public.reservations;

-- Define clean policies
create policy "Public read menu" on public.menu for select using (true);
create policy "Users manage own profiles" on public.users for all using (auth.uid() = id);
create policy "Users read own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users insert own orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Users read own reservations" on public.reservations for select using (auth.uid() = user_id);
create policy "Users insert own reservations" on public.reservations for insert with check (auth.uid() = user_id);

-- ==========================================
-- 4. AUTOMATION (TRIGGER & ADMIN LOGIC)
-- ==========================================

create or replace function public.handle_new_user()
returns trigger as $$
declare
  v_role text := 'user';
begin
  -- Auto-admin logic for specific email
  if (new.email = 'admin@gmail.com') then
    v_role := 'admin';
  end if;

  insert into public.users (id, nickname, role)
  values (
    new.id,
    split_part(new.email, '@', 1),
    v_role
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 5. INITIAL DATA (SEEDS)
-- ==========================================

-- Clean old menu (optional, safe for first run)
-- truncate table public.menu cascade;

insert into public.menu (name, price, category, description, file_name, active, weight) values
('Retro Burger', 12.99, 'burgers', 'Classic double patty burger', 'burger.jpg', true, '450g'),
('Chicken Wrap', 11.50, 'burgers', 'Tender grilled chicken wrap', 'wrap.jpg', true, '300g'),
('Arcade Nachos', 10.99, 'combos', 'Loaded corn chips with cheese', 'nachos.jpg', true, '300g'),
('Classic Lemonade', 3.50, 'drinks', 'Freshly squeezed lemonade', 'limonada.jpg', true, '400ml'),
('Vintage Milkshake', 6.50, 'drinks', 'Thick strawberry shake', 'milkshake.jpg', true, '400ml'),
('Chicken Noodle Soup', 5.90, 'soups', 'Comforting chicken broth', 'sopa_pollo.jpg', true, '350ml'),
('Mediterranean Salad', 8.90, 'salads', 'Fresh Greek-style salad', 'mediterranea.jpg', true, '300g'),
('Cheesecake', 5.80, 'desserts', 'Creamy strawberry cheesecake', 'cheesecake.jpg', true, '140g');
