-- ==========================================
-- 1. CONFIGURATION
-- ==========================================
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

-- ==========================================
-- 2. TABLES
-- ==========================================

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text unique not null,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default now()
);

create table public.menu (
  id bigint generated by default as identity primary key,
  name text not null,
  weight text,
  ingredients text,
  description text,
  price float8 not null,
  active boolean default true,
  file_name text,
  category text check (category in ('burgers', 'drinks', 'combos', 'soups', 'desserts', 'salads'))
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  total_price float8 default 0.0,
  state text default 'pending' check (state in ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled')),
  order_time timestamp with time zone default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  menu_id bigint references public.menu(id) on delete set null,
  quantity int not null check (quantity > 0),
  unit_price float8 not null
);

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  time_start timestamp with time zone not null,
  type_table text,
  user_id uuid references public.users(id) on delete cascade,
  status text default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamp with time zone default now()
);

-- ==========================================
-- 3. SECURITY & INDICES
-- ==========================================

create index idx_orders_user on public.orders(user_id);
create index idx_order_items_order on public.order_items(order_id);

alter table public.users enable row level security;
alter table public.menu enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reservations enable row level security;

-- Policies
create policy "Public read menu" on public.menu for select using (true);
create policy "Users manage own profiles" on public.users for all using (auth.uid() = id);
create policy "Users manage own orders" on public.orders for all using (auth.uid() = user_id);
create policy "Users manage own reservations" on public.reservations for all using (auth.uid() = user_id);
create policy "Users read own order items" on public.order_items for select using (
  exists (select 1 from public.orders where id = order_items.order_id and user_id = auth.uid())
);

-- ==========================================
-- 4. AUTOMATION
-- ==========================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, nickname, role)
  values (new.id, split_part(new.email, '@', 1), 'user')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 5. INITIAL DATA
-- ==========================================

insert into menu (name, price, category, description, file_name, active) values
('Retro Burger', 12.99, 'burgers', 'Classic double patty burger', 'burger.jpg', true),
('Arcade Nachos', 10.99, 'combos', 'Loaded corn chips', 'nachos.jpg', true),
('Vintage Milkshake', 6.50, 'drinks', 'Thick vanilla strawberry shake', 'milkshake.jpg', true);
