-- 1. Tabla de Usuarios
create table users (
  id bigint generated by default as identity primary key,
  nickname text unique not null,
  email text unique not null,
  password text not null,
  role text default 'user'
);

-- 2. Tabla de Menú
create table menu (
  id bigint generated by default as identity primary key,
  name text not null,
  weight text,
  ingredients text,
  description text,
  price float8,
  active boolean default true,
  file_name text,
  category text
);

-- 3. Tabla de Reservas
create table reservations (
  id bigint generated by default as identity primary key,
  time_start timestamp with time zone not null,
  type_table text,
  user_id bigint references users(id),
  status text default 'pending'
);

-- 4. Tabla de Pedidos
create table orders (
  id bigint generated by default as identity primary key,
  order_list jsonb default '{}'::jsonb,
  order_time timestamp with time zone default now(),
  total_price float8 default 0.0,
  state text default 'confirmed',
  user_id bigint references users(id)
);

-- 5. Inserción de TODOS los platos (Menú)
insert into menu (id, name, weight, ingredients, description, price, active, file_name, category) values
(6, 'Retro Burger', '450', 'Beef Patty, Cheddar Cheese, Lettuce & Tomato, Secret Sauce, Brioche Bun', 'Classic double patty with melted cheese, lettuce, and secret diner sauce.', 12.99, true, 'burger.jpg', 'burgers'),
(7, 'Arcade Nachos', '300', 'Corn Tortilla Chips, Nacho Cheese Sauce, Pickled Jalapeños, Fresh Salsa, Sour Cream', 'Loaded corn chips with jalapeños, melted cheese, and salsa.', 10.99, true, 'nachos.jpg', 'combos'),
(8, 'Chicken Wrap', '300', 'Grilled Chicken, Flour Tortilla, Mixed Greens, Tomatoes, Garlic Sauce', 'Tender grilled chicken with fresh veggies and garlic yogurt sauce.', 11.50, true, 'wrap.jpg', 'burgers'),
(9, 'Crispy Fries', '200', 'Crinkle-cut Potatoes, Vegetable Oil, Retro Salt Blend, Paprika, Garlic Powder', 'Crispy crinkle-cut fries seasoned with our special retro spice blend.', 4.99, true, 'fries.jpg', 'combos'),
(10, 'Vintage Milkshake', '400', 'Whole Milk, Vanilla Ice Cream, Fresh Strawberries, Whipped Cream, Maraschino Cherry', 'Thick vanilla strawberry shake topped with whipped cream and a cherry.', 6.50, true, 'milkshake.jpg', 'drinks'),
(11, 'Classic Pizza', '250', 'Pizza Dough, Tomato Sauce, Mozzarella Cheese, Premium Pepperoni, Italian Herbs', 'Cheesy pepperoni slice baked in our classic brick oven.', 14.99, true, 'pizza.jpg', 'combos'),
(12, 'Classic Lemonade', '400', 'Water, Freshly Squeezed Lemon, Sugar, Ice', 'Natural freshly squeezed lemonade, served with ice and a fresh lemon slice.', 3.50, true, 'limonada.jpg', 'drinks'),
(13, 'Natural Orange Juice', '350', 'Fresh Oranges', '100% natural orange juice, freshly squeezed, with no added sugars.', 3.80, true, 'naranja.jpg', 'drinks'),
(14, 'Iced Tea', '450', 'Black Tea, Lemon or Peach, Mint', 'Black iced tea with a touch of lemon or peach and fresh mint leaves.', 3.20, true, 'iced_tea.jpg', 'drinks'),
(15, 'Strawberry Milkshake', '400', 'Whole Milk, Fresh Strawberries', 'Delicious creamy milkshake made with fresh strawberries and whole milk.', 4.50, true, 'batido.jpg', 'drinks'),
(16, 'Americano Coffee', '250', 'Ground Coffee, Water', 'Freshly roasted and ground coffee, served hot or on the rocks.', 2.80, true, 'cafe.jpg', 'drinks'),
(17, 'Sparkling Mineral Water', '400', 'Sparkling Water, Lemon Slice', 'Sparkling mineral water served with a touch of lemon.', 2.50, true, 'agua_gas.jpg', 'drinks'),
(18, 'Chicken Noodle Soup', '350', 'Chicken Broth, Noodles, Carrot, Celery', 'Comforting chicken broth with noodles, carrots, and celery.', 5.90, true, 'sopa_pollo.jpg', 'soups'),
(19, 'Vegetable Cream Soup', '350', 'Zucchini, Carrot, Potato, Heavy Cream', 'Smooth cream soup made with zucchini, carrots and potatoes.', 6.20, true, 'crema_verduras.jpg', 'soups'),
(20, 'Minestrone Soup', '400', 'Pasta, Tomatoes, Beans, Fresh Vegetables', 'Traditional soup with pasta, tomatoes, beans, and fresh vegetables.', 6.50, true, 'minestrone.jpg', 'soups'),
(21, 'Beef Consommé', '300', 'Beef Broth, Diced Vegetables', 'Traditional beef broth accompanied by small diced vegetables.', 5.50, true, 'consome.jpg', 'soups'),
(22, 'Tomato and Basil Soup', '350', 'Ripe Tomatoes, Fresh Basil, Croutons', 'Soup made with ripe tomatoes and fresh basil, served with croutons.', 5.80, true, 'sopa_tomate.jpg', 'soups'),
(23, 'Homemade Lentil Soup', '400', 'Lentils, Carrot, Potato, Spices', 'Slow-cooked lentil soup with carrots, potatoes, and spices.', 6.00, true, 'lentejas.jpg', 'soups'),
(24, 'Classic Burger Combo', '600', 'Beef Patty, Cheddar Cheese, Lettuce, Tomato, French Fries, Soft Drink', 'Beef burger with lettuce, tomato, cheese, fries and soft drink.', 14.90, true, 'combo_burger.jpg', 'combos'),
(25, 'Chicken Wings Box', '450', 'Chicken Wings, BBQ Sauce, French Fries', '6 crispy chicken wings with BBQ sauce and french fries.', 13.50, true, 'alitas.jpg', 'combos'),
(26, 'Chicken Sandwich Combo', '450', 'Chicken Breast, Lettuce, Mayonnaise, French Fries', 'Grilled chicken breast sandwich with lettuce, mayo and side fries.', 12.50, true, 'combo_sand_pollo.jpg', 'combos'),
(27, 'Vegetarian Box', '400', 'Wheat Tortilla, Hummus, Avocado, Vegetables', 'Fresh vegetable wrap with hummus and avocado, with salad.', 12.90, true, 'box_veggie.jpg', 'combos'),
(28, 'Chicken Tenders Combo', '400', 'Breaded Chicken Breast, French Fries, Ranch Dressing', '4 breaded chicken breast strips with fries and ranch dressing.', 11.90, true, 'tenders.jpg', 'combos'),
(29, 'Club Sandwich Combo', '500', 'Chicken, Bacon, Cheese, Lettuce, Tomato, French Fries', 'Three-layer sandwich with chicken, bacon, cheese and fries.', 13.90, true, 'club_sandwich.jpg', 'combos'),
(30, 'Apple Tart', '150', 'Apple, Cinnamon, Puff Pastry', 'Slice of baked apple tart with a hint of cinnamon.', 5.50, true, 'tarta_manzana.jpg', 'desserts'),
(31, 'Cheesecake', '140', 'Cream Cheese, Biscuit, Strawberry Jam', 'Creamy cheesecake with a biscuit base and strawberry jam.', 5.80, true, 'cheesecake.jpg', 'desserts'),
(32, 'Brownie with Walnuts', '100', 'Chocolate, Walnuts, Sugar, Egg', 'Portion of rich, intense chocolate brownie with walnuts.', 4.50, true, 'brownie.jpg', 'desserts'),
(33, 'Fresh Fruit Salad', '200', 'Melon, Pineapple, Grape, Banana, Yogurt', 'Bowl of seasonal fresh fruits with yogurt.', 4.80, true, 'ensalada_frutas.jpg', 'desserts'),
(34, 'Vanilla Flan', '120', 'Egg, Milk, Vanilla, Caramel', 'Classic caramel egg custard, smooth and creamy.', 4.20, true, 'flan.jpg', 'desserts'),
(35, 'Waffle with Fruits', '220', 'Flour, Syrup, Strawberries, Banana', 'Crispy waffle served with syrup and strawberries or banana.', 6.50, true, 'waffle.jpg', 'desserts'),
(36, 'Mediterranean Salad', '300', 'Lettuce, Cherry Tomato, Cucumber, Olives, Feta Cheese, Olive Oil', 'Fresh lettuce, cherry tomatoes, cucumber, olives, and feta cheese.', 8.90, true, 'mediterranea.jpg', 'salads'),
(37, 'Chickpea Veggie Burger', '450', 'Chickpeas, Spices, Brioche Bun, Avocado, Vegan Mayonnaise, French Fries', 'Chickpea burger on brioche bun with avocado and fries.', 10.50, true, 'hamb_veggie.jpg', 'burgers'),
(38, 'Halloumi Cheese Wrap', '380', 'Wheat Tortilla, Halloumi Cheese, Peppers, Arugula, Yogurt Sauce', 'Tortilla filled with grilled halloumi cheese and roasted peppers.', 9.50, true, 'wrap_veggie.jpg', 'burgers'),
(39, 'Caprese Sandwich', '300', 'Sourdough Bread, Tomato, Fresh Mozzarella, Basil, Balsamic Vinegar', 'Sourdough bread with tomato, fresh mozzarella, and basil.', 8.50, true, 'caprese.jpg', 'burgers'),
(40, 'Quinoa Bowl with Vegetables', '400', 'Quinoa, Avocado, Zucchini, Eggplant, Peppers, Sesame Seeds', 'Quinoa bowl with avocado and roasted vegetables.', 10.90, true, 'quinoa_bowl.jpg', 'salads'),
(41, 'Pesto Pasta with Cherry Tomatoes', '350', 'Pasta, Basil, Pine Nuts, Parmesan, Cherry Tomatoes', 'Pasta tossed in fresh basil pesto with cherry tomatoes.', 9.80, true, 'pesto.jpg', 'salads'),
(42, 'Pumpkin and Ginger Cream Soup', '350', 'Pumpkin, Ginger, Pumpkin Seeds', 'Cream soup made of baked pumpkin with a spicy touch of ginger.', 6.50, true, 'crema_calabaza.jpg', 'soups');
