-- 00_initial_schema.sql
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text unique not null,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default now()
);

create table public.menu (
  id bigint generated by default as identity primary key,
  name text not null,
  weight text,
  ingredients text,
  description text,
  price float8 not null,
  active boolean default true,
  file_name text,
  category text check (category in ('burgers', 'drinks', 'combos', 'soups', 'desserts', 'salads')),
  created_at timestamp with time zone default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete set null,
  total_price float8 default 0.0,
  state text default 'pending' check (state in ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled')),
  order_time timestamp with time zone default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  menu_id bigint references public.menu(id) on delete set null,
  quantity int not null check (quantity > 0),
  unit_price float8 not null,
  created_at timestamp with time zone default now()
);

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  time_start timestamp with time zone not null,
  type_table text,
  user_id uuid references public.users(id) on delete cascade,
  status text default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamp with time zone default now()
);
